apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-staging
  namespace: argocd
spec:
  project: default
  sources:
    # 1) Chart from your charts repo (Git)
    - repoURL: https://github.com/priyajithc/sample-system.git
      targetRevision: main
      path: charts/backend
      helm:
        releaseName: backend
        valueFiles:
          - $values/apps/backend/staging/values.yaml   # <- env values from GitOps repo
    # 2) Values-only source from your GitOps repo
    - repoURL: https://github.com/priyajithc/sample-system-ops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
